(require 'spacing-algorithm)

(defvar quenya-lesson
	'((2 . (("one" . "minë")
		("the Sun" . "Anar")
		("the Moon" . "Isil")
		("and" . "ar")
		("Elf" . "Elda")
		("people" . "lië")
		("maiden" . "vende")
		("horse" . "rocco")
		("king" . "aran")
		("queen" . "tári")
		("willow" . "tasar")
		("under" ."nu")
		("Plural nouns ending in -a, -i, -o, -u and -ie the end in -" . "r")
		("In plural nouns ending in -e the -e is replaced by -" . "i")
		("Plural nouns ending with a consonant end in -" . "i")
		("The definite article (\"the\") is " . "i")
		("The indefinite article (\"a\") is " . "")
		("roccor" . "horses")
		("aran" . "king")
		("i rocco" . "the horse")
		("i roccor" . "the horses")
		("arani" . "kings")
		("minë lië nu minë aran" . "one people under one king")
		("i aran ar i tári" . "the king and the queen")
		("vendi" . "maidens")
		("willows" . "tasari")
		("elves" . "eldar")
		("the kings" . "i arani")
		("peoples" . "lier")
		("the horse under the willow" . "i rocco nu i tasar")
		("a maiden and a queen" . "vendë ar tári")
		("the queen and the maidens" . "i tári ar i vendi")
		("the Sun and the Moon" . "Anar ar Isil")
		))
	    (3 . (("two" . "atta")
		  ("eye" . "hen")
		  ("arm" . "ranco")
		  ("gate" . "ando")
		  ("ship" . "cirya")
		  ("bird" . "aiwë")
		  ("floor" . "talan")
		  ("man" . "nér")
		  ("woman" . "nís")
		  ("stone" . "sar")
		  ("mountain" . "oron")
		  ("Dual nouns (that don't contain a t or d) end in -" . "t")
		  ("Dual nouns that contain a t or d end in -" . "u")
		  ("Dual nouns that are body parts end in -" . "u")
		  ("hendu" . "a pair of eyes")
		  ("atta hendi" . "two eyes")
		  ("aldu" . "a pair of trees")
		  ("atta aldar" . "two trees")
		  ("minë nér ar minë nís" . "one man and one woman")
		  ("i sardi" . "the stones")
		  ("talami" . "floors")
		  ("oronti" . "mountains")
		  ("two ships" . "atta ciryar")
		  ("two sister ships" . "ciryat")
		  ("arms" . "rancu")
		  ("twin mountains" . "orontu")
		  ("double gate" . "andu")
		  ("a pair of birds" . "aiwet")
		  ("two birds" . "atta aiwi")
		  ("men and women" . "neri ar nissi")
		  ))
	    (4 . (("three" . "neldë")
		  ("is" . "ná")
		  ("are" . "nar")
		  ("beautiful, fair" . "vanya")
		  ("great, big" . "alta")
		  ("bright" . "calima")
		  ("mighty" . "taura")
		  ("wise" . "saila")
		  ("evil" . "úmëa")
		  ("red" . "carnë")
		  ("white" . "ninquë")
		  ("black" . "morë")
		  ("dead" . "firin")
		  ("Adjectives ending in -a have plural forms in -" . "ë")
		  ("Adjectives ending in -eä have plural forms in -" . "ië")
		  ("Adjectives ending in -ë have plural forms in -" . "i")
		  ("morë rocco" . "black horse")
		  ("calimë hendu" . "bright pair of eyes")
		  ("neldë firini neri" . "three dead men")
		  ("vanyë aiwi" . "beautiful birds")
		  ("tári ná taura nís" . "a queen is a mighty woman")
		  ("i oronti nar altë" . "the mountains are great")
		  ("aran taura" . "a king is mighty")
		  ("i nér ar i nís nar sailë" . "the man and the woman are wise")
		  ("the white gate" . "i ninquë ando")
		  ("a great ship" . "alta cirya")
		  ("the floor is red" . "i talan ná carnë")
		  ("one black stone and three white stones" . "minë morë sar ar neldë ninqui sardi")
		  ("wise kings are mighty men" . "sailë arani nar taurë neri")
		  ("the mighty man and the beautiful woman are evil" .
		   "i taura nér ar i vanya nís nar úmië")
		  ("elves are beautiful" . "eldar nar vanyë")
		  ("the elves are a beautiful people" . "i eldar nar vanya lië")
		  ))
	    (5 . (("four" ."canta")
		  ("Dwarf" . "Nauco")
		  ("book" . "parma")
		  ("thick, fat" . "tiuca")
		  ("grasp, seize" . "mapa-")
		  ("watch, guard" . "tir-")
		  ("laugh" . "lala-")
		  ("lie (lie horizontally, not \"tell a lie\")" . "caita-"  )
		  ("summon" . "tulta-")
		  ("sing" . "linda-")
		  ("eat" . "mat-") 
		  ("read" . "cenda-")
		  ("The present tense of a verb has a long " . "stem-vowel")
		  ("The present tense of a primary verb ends in -" . "a")
		  ("The present tense of an A-stem replace the -a ending by -" . "ëa")
		  ("The present tense does not have a long stem-vowel if it is followed by a "
	. "consonant cluster")
		  ("The superlative form of an adjective (brightest) has a prefix " . "an")
		  
		  ))
            (6 . (("five" . "lempë")
                  ("star" . "elen")
                  ("treasure" . "harma")
                  ("shine" . "sil-")
                  ("find" . "hir-")
                  ("jump" . "cap-")
                  ("write" . "tec-")
                  ("speak, say" . "quet-")
                  ("love" . "mel-")
                  ("see" . "cen-")
                  ("rise" . "orta-")
                  ("possess; have" . "harya-")
                  ("The past tense of a A-stem verb ends in -" . "në")
                  ("The past tense of a primary verb ending in -r,m,n end in -" . "në")

                  ("The past tense of a primary verb ending in -l ends in -" . "lë")
                  ("The past tense of a primary verb ending in -p,t,c ends in -"
            . "ë")
                  ("The past tense of a primary verb ending in -p,t,c recieves a "
            . "nasal-infixion")
                  ("i nér cendanë i parma" . "the man read the book")
                  ("i Naucor manter" . "the Dwarves ate")
                  ("i aran tultanë i tári" . "the king summoned the queen")
                  ("nís lindanë" . "a woman sang")
                  ("i vendi tirner i Elda" . "the maidens watched the elf")
                  ("i lempë roccor caitaner nu i alta tasar" .
                   "the five horses lay under the big willow")
                  ("i eleni siller" . "the stars shone")
                  ("i Nauco cennë rocco" . "the Dwarves saw a horses")
                  ("a Dwarf found the treasure" . "Nauco hirnë i harma")
                  ("the Elf spoke" . "i Elda quentë")
                  ("the horse jumped" . "i rocco campë")
                  ("the king loved the Elves" . "i aran mellë i Eldar")
                  ("a man wrote five books" . "nér tencë lempë parmar")
                  ("the queen rose" . "i tári ortanë")
                  ("the kings possessed great treasures" .
                   "i arani haryaner altë harmar")
                  ("the king and the queen summoned four Elves and five Dwarves" .
                   "i aran ar i tári tultaner canta Eldar ar lempë Nauror")
                  ))
            (7 . (("six" . "enquë")
                  ("all, every" . "ilya")
                  ("many" . "rimba")
                  ("Man (mortal man, not male)" . "Atan")
                  ("warrior" . "ohtar")
                  ("lion" . "rá")
                  ("the World" . "Ambar")
                  ("flesh" . "hrávë")
                  ("sword" . "macil")
                  ("die, expire" . "fir-")
                  ("govern, control, wield" . "tur-")
                  ("over, above" . "or")
                  ("The future tense of a verb ends in -" . "uva")
                  ("In the future tense of a-stem verds the -a ending is" . "dropped")
                  ("The difference between the aorist and present tense is that the
                  aorist is " . "durationless")
                  ("Is 'is speaking' present tense or aorist?" . "present tense")
                  ("Is 'speaks' present tense or aorist?" . "aorist")
                  ("The aorist of a-stem verbs ends in -" . "")
                  ("The aorist af primary verbs (without other endings) ends in -"
                  . "ë")
                  ("The aorist af primary verbs (with another ending) ends in -"
                  . "i")
                  ("rimbë Naucor hayar harmar" . "many Dwarves possess treasures")
                  ("Anar ortuva ar i aiwi linduvar" .
                   "the Sun will rise and the birds will sing")
                  ("enquë neri tiruvar i ando" . "six men will guard the gate")
                  ("ilya Atan firuva" . "every Man will die")
                  ("ilyë Atani firir" . "all Men die")
                  ("saila nér cenda rimbë parmar" . "a wise man reads many books")
                  ("ilya elen silë or Ambar" . "every star shines above the World")
                  ("i Elda mapa i Nauco" . "the Elf seizes the Dwarf")
                  ("every Elf and every Man" . "ilya Elda ar ilya Atan")
                  ("the Elf will find the Dwarf" . "i Elda hiruva i Nauco")
                  ("the horse jumps over the Dwarf" . "i rocco capë or i Nauco")
                  ("the king controls many warriors and will contol all the World"
                  . "i aran turë rimbë ohtari ar turuva ilya Ambar")
                  ("the king and the queen will read the book" .
                   "i aran ar i tári cenduvar i parma")
                  ("the warrior wields a sword" . "i ohtar turë macil")
                  ("all lions eat flesh" . "ilya rávi matir hrávë")
                  ("six lions are eating flesh" . "enquë rávi mátar hrávë")
                  ))
            (8 . (("seven" . "otso")
                  ("boy" . "seldo")
                  ("thrall, slave" . "mól")
                  ("for" . "an")
                  ("come" . "tul-")
                  ("fall (verb)" . "lanta-")
                  ("hide" . "nurta-")
                  ("release, set free" . "lerya-")
                  ("end (put an end to)" . "metya-")
                  ("pursue" . "roita-")
                  ("bless, praise" . "laita-")
                  ("between" . "imbë")
                  ("The perfect tense is formed by adding the ending" .  "-ië")
                  ("The perfect tense has a long" . "stem-vowel")
                  ("The perfect tense of ric- is" . "irícië")
                  ("The perfect tense of hanya- is" . "ahánië")
                  ("The pronoun 'I' adds the ending -" . "nyë")
                  ("The pronoun 'thou, you' adds the ending -" . "lyë")
                  ("The pronoun 'it' adds the ending -" . "s")
                  ("i nér ihírië i harma" . "the man has found the treasure")
                  ("i rávi amátier i hrávë" . "the lions have eaten the flesh")
                  ("i aran utultië i tári" . "the king has summoned the queen")
                  ("i nissi ecendier i parma" . "the women have read the book")
                  ("i úmëa tári amápië i otso Naucor" .
                   "the evil queen has seized the seven Dwarves")
                  ("etécielyë otso parmar" . "you have written seven books")
                  ("equétien" . "i have spoken")
                  ("ecénielyes" . "you have seen it")
                  ("the man has come" . "i nér utúlië")
                  ("the seven Dwarves have eaten" . "i otso Naucor amátier")
                  ("the boys have seen a lion between the trees" .
                   "i seldor ecénier rá imbë i aldar")
                  ("the six Elves have pursued the seven Dwarves" .
                   "i enquë Eldar oroitier i otso Naucor")
                  ("the Dwarf has hidden a treasure" . "i Nauco unurtië harma")
                  ("I have praised the king, for the king has released all thralls"
                  . "alaítienyë i aran, an i aran elérië ilyë móli")
                  ("you have fallen, and I have seen it" .
                   "alántielyë, ar ecénienyes")
                  ("I have put an end to it" . "emétienyes")
                  ))
            )
	"Contains the vocabularies and summaries for each lesson")

(defun quenya-add-lesson (lesson)
  "Adds a lesson to the spacing-algorithm queue"
  (interactive "nLesson number: ")
  (spacing-algorithm-add-list (cdr (assoc lesson quenya-lesson)))
  )

(defun spacing-algorithm-add-list (list)
    (spacing-algorithm-load)
    (dolist (item list)
      (spacing-algorithm-add-item item))
    (spacing-algorithm-save)
  )

(provide 'quenya)
;;(require 'spacing-simple)
